const sorcerer = [
{
    name:"Malevolent Shrine",
    jname:"Fukuma Mizushi",
    user:"Ryomen Sukuna",
    age:"1000+",
    species:"Human/Incarnation",
    grade:"Special Grade",
    domainname:"Malevolent Shrine (Fukuma Mizushi) is Sukuna's domain expansion.",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span> Ryomen Sukuna, is the strongest jujutsu sorcerer from a thousand years ago. Regarded as the undisputed King of Curses, Sukuna is one of the primary antagonists of the Jujutsu Kaisen series. According to legend, Sukuna was an Imaginary Demon during the Heian Era but in truth he was a sorcerer also known as the Disgraced One. Sukuna is around 1000+ years old and was a human now incarnate using the boding of itadori as his host.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span> Malevolent Shrine constructs an environment centered around a small,  Buddhist shrine that has been distorted to instead enshrine demons. It is surrounded by dark-colored water and horned, bull-like skulls on the ground. Human skulls that hang down from it. The four entrances to the shrine are formed by large, grotesque mouths, complete with humanlike teeth and tongues.",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span> Sukuna has the ability to expand his domain without closing the barrier. Creating a binding vow due to allowing an escape route from the domain that enables him to expand the range of the guaranteed-hit up to a maximum radius of <span style='color: deepskyblue;'>200 meters</span>. Malevolent Shrine cannot be destroyed because of the lack of an enclosed barrier. ",
    appear:"./assets/shrine.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span> Malevolent Shrine's guaranteed-hit ability can be made to relentlessly slash apart anything until nothing but dust remains of what has caught in the effective range, via Sukuna's two types of slashing attacks: Cleave and Dismantle, which only cease when the domain is disengaged or Sukuna is so badly injured he can not sustain the domain anymore. Sukuna can set which of the two attacks to use against specific types of targets, such as using <span style='color: deepskyblue;'>Dismantle</span> for inanimate objects and <span style='color: deepskyblue;'>Cleave</span> for subjects with cursed energy.",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span> <span style='color: deepskyblue;'>fukuma</span>(伏魔), comes from <span style='color: deepskyblue;'>fukumaden</span>(伏魔殿), referring to a palace where demons lurk, and is also translatable as <span style='color: deepskyblue;'>Pandemonium</span>.<br>Honorific prefix <span style='color: deepskyblue;'>mi</span> (御), a <span style='color: deepskyblue;'>zushi</span>(厨子) is a miniature, double-doored Buddhist shrine or <span style='color: deepskyblue;'>zu/kuriya</span>(厨) meaning <span style='color: deepskyblue;'>Kitchen</span>.",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span> During his battle with Satoru Gojo, Sukuna expanded his domain a total of <span style='color: deepskyblue;'>three</span> times. As previously mentioned, Malevolent Shrine can equal Unlimited Void in a domain clash, but that is only the case inside a barrier.<br><br> Malevolent Shrine's range reached beyond Unlimited Void's barrier during the first clash of domains. With a domain's barrier being weak to attacks on its outer shell, Gojo's domain was crushed by Malevolent Shrine's slashing attacks and he was immediately struck by its can't-miss attack. <br><br>Later in the fight, Sukuna revealed that he can change the conditions of his domain with a binding vow, such as removing Malevolent Shrine's guaranteed-hit effect within Unlimited Void's effective area or narrowing down its effective range similar to when it was used in Shibuya in exchange for increased power to counter Gojo's Unlimited Void's reinforced outer shell, collapsing it a second time.",
    userimage:"./user/sukuna3.png",
    hand:"./assets/200.jpg",
    domainimage:"./assets/shrine.jpg",
    domainvid:"./assets/cleave.mp4",
    back:"./domain/shrine.png", 
    full:"./user/2sukuna.png",
    manga:"<span style='color: orange; font-weight:900;'>Manga:</span> Chapter 8",
    anime:"<span style='color: orange; font-weight:900;'>Anime:</span> Episode 4",
},
{
    name:"Unlimited Void",
    jname:"Muryōkūsho",
    user:"Satoru Gojo",
    age:"29",
    species:"Human",
    grade:"Special Grade",
    domainname:"Unlimited Void (Muryōkūsho?) is Satoru Gojo's domain expansion.",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span> Satoru Gojo is one of the main protagonists of the Jujutsu Kaisen series. He is a special grade jujutsu sorcerer and widely recognized as the strongest in the world. Satoru is the pride of the Gojo Clan, the first person to inherit both the Limitless and the Six Eyes in four hundred years. He works as a teacher at the Tokyo Jujutsu High and uses his influence to protect and train strong young allies. He is a human born <span style='color: deepskyblue;'>December 7, 1989</span> making him <span style='color: deepskyblue;'>29</span>.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span> This otherworldly space is characterized by a vast and seemingly infinite swirling blackness, devoid of any discernible landmarks or boundaries. The atmosphere is thick with an eerie energy. Inky black tendrils and ethereal shadows weaves through the void, giving it an almost liquid quality. In the center what seems to be a black hole this domain seems as if there are in space.",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span> Unlimited Void is one of, if not the most advanced technique in the arsenal of the Limitless. Satoru Gojo inherited the <span style='color: deepskyblue;'>Six Eyes</span> and likely mastered his Domain Expansion after awakening his full potential after the Star Plasma Vessel escort mission. He first displayed his mastery over his domain when he used it to counter Jogo's domain.",
    appear:"./assets/void.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span> This Domain Expansion brings the user and their targets inside the Limitless itself, a vast void of infinite knowledge. Boundless raw information floods into the target's mind, overwhelming them to the point where they're completely immobilized. Alongside Self-Embodiment of Perfection, Nanami considered Unlimited Void an almost-guaranteed win once it ensnares its target.<br><br>The complete incapacitation of the target is caused by a phenomenon where the target will be able to see and feel everything while not being able to see or feel anything at the same time. All the actions one has taken in their life is forced upon them infinitely and they can't do anything but die slowly. This effect does not affect the user or anyone they're touching.",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span> 無量空処 <span style='color: deepskyblue;'>(Muryōkūsho)</span> is a Buddhist term that can be translated as the <span style='color: deepskyblue;'>Unlimited Void</span> or <span style='color: deepskyblue;'>Infinite Space</span>.<br> Often used in the context of Buddhist philosophy to describe a boundless and infinite space transcending conventional notions of physical dimensions.",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span>  Satoru surprised everyone and activated an all-or-nothing Domain Expansion of just <span style='color: deepskyblue;'>0.2 seconds</span>. Figuring that a non-sorcerer could only last 0.2 seconds within the domain without suffering aftereffects. The amount of information that everyone was exposed to was about half a year's worth, leaving everyone unconscious while still standing. This level of the domain could've allowed the cursed spirits to awaken from their trance at any moment, so Satoru focused on eliminating all one thousand of the transfigured humans targeting the civilians in just 299 seconds.<br><br>During Satoru's duel with Sukuna, he expanded Unlimited Void a total of <span style='color: deepskyblue;'>five</span> times. The two of them simultaneously activated Domain Expansion after various well-matched exchanges. Unlimited Void proved to be as equally strong as Sukuna's Malevolent Shrine, neutralising both of their guaranteed-hit effects.",
    domainimage:"",
    hand:"./assets/eyes.jpg",
    domainvid:"./assets/void.mp4",
    manga:"<span style='color: orange; font-weight:900;'>Manga:</span> Chapter 15",
    anime:"<span style='color: orange; font-weight:900;'>Anime:</span> Episode 7",
    userimage:"./user/gojo.png",
    back:"./domain/void.png",
    full:"./user/1gojo.png",
},
{
    name:"Chimera Shadow Garden",
    jname:"Kangō An'eitei",
    user:"Megumi Fushiguro",
    age:"16",
    species:"Human",
    grade:"Grade 2",
    domainname:"Chimera Shadow Garden (Kangō An'eitei) is Megumi Fushiguro's domain expansion using the Ten Shadows Technique.",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span> Megumi Fushiguro  is the deuteragonist of the Jujutsu Kaisen series. He is a grade 2 jujutsu sorcerer and first-year student at Tokyo Jujutsu High. Megumi is the step-brother of Tsumiki Fushiguro and as the son of Toji Fushiguro, Megumi is also a descendant of the Zenin Clan. Born <span style='color: deepskyblue;'>December 22, 2002</span> making him <span style='color: deepskyblue;'>16</span> years old.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span> While <span style='color: deepskyblue;'>incomplete</span>, Chimera Shadow Garden floods the area with thick fluid shadows. With an <span style='color: deepskyblue;'>enclosed</span> barrier, the domain traps the target inside the user's shadow, recoloring the entire space into black. It also conjures a large object that resembles two columns of a spinal bone with bow-shaped ropes tied and roots attached to it. This <span style='color: deepskyblue;'>disappears</span> soon after the initial casting.",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Weakness:</span> Megumi can keeps items in his shadow but he must bear their <span style='color: deepskyblue;'>weight</span>. Reggie used Megumi's shadow against him by summoning three cars and dropping them into the domain causing immense pressure and weight onto Megumi. This made megumi incompacitated unable to move freely due to the weight he must endure so his domain does not break.<br>",
    appear:"./assets/shadow.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span> Chimera Shadow Garden floods the area with thick fluid shadows. This grants the user the ability to manifest multiple shikigami, as well as advanced manipulation of all available shadows. He is also able to make shadow <span style='color: deepskyblue;'>clones</span> of himself out of the black fluid as well as hide inside as if the fluid is a huge shadow. Though this domain does <span style='color: deepskyblue;'>not have a sure-hit effect</span> it only <span style='color: deepskyblue;'>amplifies</span> the users abilities.<br><br>Anyone standing in the shadow will have to reinforce their feet with cursed energy or risk falling into the abyss. Within the liquid-like shadows, there is no <span style='color: deepskyblue;'>buoyancy, resistance</span> , or <span style='color: deepskyblue;'>oxygen</span>. Anyone who has dropped into it will fall indefinitely.",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span> The firat kanji <span style='color: deepskyblue;'>嵌</span> (Kan) means <span style='color: deepskyblue;'>Embed, fit into</span>. While the rest of the Kanji translates to:<br> <span style='color: deepskyblue;'>暗</span> (An) - <span style='color: deepskyblue;'>Dark</span><br> <span style='color: deepskyblue;'>翳</span> (Ei) - <span style='color: deepskyblue;'>Shadow</span><br> <span style='color: deepskyblue;'>庭</span> (Tei) - <span style='color: deepskyblue;'>Garden</span><br> representing his domain",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span> Megumi first manifested Chimera Shadow Garden in a battle by freely imagining himself going beyond his limits. The activation of this technique used nearly all of Megumi's cursed energy, resulting in physical backlash. This coupled with Megumi's inexperience resulted in an improper Domain Expansion without a complete barrier or a must-hit effect. Even so, the domain was effective enough to enhance Megumi's Ten Shadows Technique to a greater degree than normal.<br><br>While fighting in the Culling Game, with his domain still incomplete, it would've been foolish to cast it without being able to trap his opponents. Instead, Megumi was able to separate Reggie from his partner and lure him into a spacious gymnasium he deemed a perfect fit for his domain. Unable to use barrier techniques very well, Megumi forcibly enclosed the barrier by converting the gymnasium into his domain and trapped Reggie inside.",
    manga:"<span style='color: orange; font-weight:900;'>Manga:</span> Chapter 58",
    anime:"<span style='color: orange; font-weight:900;'>Anime:</span> Episode 23",
    userimage:"./user/megumi.png",
    domainimage:"",
    domainvid:"./assets/chimera.mp4",
    hand:"./assets/weakness.jpg",
    back:"./domain/chimera.png",
    full:"./user/3megumi.png",
},
{
    name:"Time Cell Moon Palace",
    jname:"Jihō Gekkyūden",
    user:"Naoya Zenin",
    age:"27",
    species:"Human/Vengeful Curse",
    grade:"Special Grade 1",
    domainname:"Time Cell Moon Palace (Jihō Gekkyūden) is Naoya Zenin's domain expansion using Projection Sorcery.",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span> Naoya Zenin is the youngest son of Naobito Zenin and believed himself to be the true heir of the Zenin Family. Naoya is also the head of the clan's elite unit of jujutsu sorcerers, the Hei. Naoya is <span style='color: deepskyblue;'>27</span> years old and is a <span style='color: deepskyblue;'>special grade 1</span> sorcerer. But was later killed by maki and reincarnated as a <span style='color: deepskyblue;'>vengeful curse</span>.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span> Expanding this domain casts a black empty area save for a few floating particles and the main stage of the environment. The primary stage of the Time Cell Moon Palace is comprised of a straight path of flesh that leads to a large eye behind the caster. Around is nothing but a dark void.<br><br><br>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span> Following his reincarnation as a vengeful cursed spirit. He no longer has a human shape, instead, his body is large and long like a <span style='color: deepskyblue;'>caterpillar</span>.<br>  His fully realized cursed form resembles a <span style='color: deepskyblue;'>chrysalis</span> with a <span style='color: deepskyblue;'>skull-shaped</span> face capable of extending <span style='color: deepskyblue;'>tendrils</span> that band together to function like humanoid limbs.",
    appear:"./assets/time.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span> The auto-hit function of the domain injects films of animation frames into the neck of its targets. Anyone who moves within the domain must abide by the <span style='color: deepskyblue;'>24FPS</span> rule of Projection Sorcery or they will receive numerous bloody injuries with every movement.<br><br>The domain increases the precision of the embedded cursed technique and targets individual cells. Freezing individual cells disrupts them and causes countless small cuts and gashes to appear all over the body, completely <span style='color: deepskyblue;'>immobilizing</span> any target. Forcing a movement can cause an <span style='color: deepskyblue;'>appendage</span> to be cut off completely.",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span> The first kanji <span style='color: deepskyblue;'>時</span> (Ji) means <span style='color: deepskyblue;'>time</span>. The rest translate to:<br> <span style='color: deepskyblue;'>胞</span> (Hō) means <span style='color: deepskyblue;'>placenta</span> or <span style='color: deepskyblue;'>childbirth</span>.<br><span style='color: deepskyblue;'>月</span> (Gatsu or getsu) means <span style='color: deepskyblue;'>moon</span>.<br><span style='color: deepskyblue;'>宮</span> (Kyū)/<span style='color: deepskyblue;'>殿</span> (Den) means <span style='color: deepskyblue;'>palace</span> or <span style='color: deepskyblue;'>hall</span><br><br><br>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span> Naoya expanded his domain for the first time when he was pushed to his limits as a vengeful cursed spirit while fighting Maki Zenin, Hagane Daido, and Rokujushi Miyo.  He trapped Daido and Miyo inside the domain and two lines of film injected into both of their necks. As nothing appeared to happen, the two fighters assumed it was a misfire and attempted to attack. <br><br>Unable to obey the 24FPS rule, Daido and Miyo suffered numerous small injuries all over their body that bled profusely. After being immobilized, Miyo collapsed and Daido attempted to slash the Split Soul Katana only for his hand to be severed. The domain was unable to recognize Maki however and couldn't target her without any cursed energy. She was able to move freely in the domain and killed Naoya by attacking him from behind.",
    manga:"<span style='color: orange; font-weight:900;'>Manga:</span> Chapter 198",
    anime:"<span style='color: orange; font-weight:900;'>Anime:</span> N/A",
    userimage:"./user/naoya.png",
    domainimage:"",
    domainvid:"./assets/film.mp4",
    hand:"./assets/curse.jpg",
    back:"./domain/cell1.png",
    full:"./user/2naoya.png",
},
{
    name:"Idle Death Gamble",
    jname:"Zasatsu Bakuto",
    user:"Kinji Hakari",
    age:"Unknown",
    species:"Human",
    grade:"Suspended",
    domainname:"Idle Death Gamble (Zasatsu Bakuto) is Kinji Hakari's domain expansion.",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span> Kinji Hakari is a third-year student at Tokyo Jujutsu High who is currently <span style='color: aqua;'>suspended</span> for clashing with authority. While away from the school, Kinji is running the <span style='color: aqua;'>Gachinko Fight Club</span>, a venue for hand-to-hand combat between sorcerers for money. Hakari is widely recognized as one of the most powerful students at Tokyo Jujutsu High. Satoru Gojo, believes that Hakari and Yuta Okkotsu will have the potential to rival his power one day.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Introduction:</span> Idle Death Gamble: <span style='color: aqua;'>CR Private Pure Love Train</span> Version <span style='color: aqua;'>1/239</span> is based on a real pachinko machine and gets its theme from the eponymously named romance manga series. The domain takes place in a <span style='color: aqua;'>train station</span> with revolving doors and train card readers. With cut scene <span style='color: aqua;'>scenarios</span> for when the Hakari hits a jackpot. For example, the transit card riichi scenario takes the user and their opponent to a different part of the train station where Yuki must pass through the gate and get to work on time to hit the jackpot.",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Jackpot:</span> Failure to hit a jackpot within a scenario will revert the stage back to the start. This will <span style='color: aqua;'>repeat</span> until the user wins or runs out of chances <span style='color: aqua;'>(39 spins)</span>. On the first activation, the probability of jackpot is over <span style='color: aqua;'>20%</span>. If a jackpot is hit, the domain disappears, and Admiring You plays, recieving a <span style='color: aqua;'>bonus</span> of <span style='color: aqua;'>unlimited cursed energy</span> for <span style='color: aqua;'>4min 11sec</span> (No restrictions). They can also receive bonus amounts randomly. This allows them to open their domain repeatedly as long as a jackpot is achieved. If the user lined up 3 <span style='color: aqua;'>odd numbers</span>, they start with <span style='color: aqua;'>advanced probability</span>. <span style='color: aqua;'>Even numbers</span>, start with <span style='color: aqua;'>faster spins</span>.",
    appear:"./assets/cut.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span> The user's goal is to hit the jackpot by lining up <span style='color: aqua;'>three</span> of the same symbols decorated with the characters. The jackpot bonus grants the user <span style='color: aqua;'>unlimited cursed energy</span> and a <span style='color: aqua;'> automatic reverse cursed technique</span> for <span style='color: aqua;'>4mins</span> and <span style='color: aqua;'>11sec</span>, the duration of the Private Pure Love Train theme song. The regeneration speed is higher than even Gojo and Sukuna's.<br><br>The user must participate in the flow of the game in order to hit jackpot, with only a <span style='color: aqua;'>1/200</span> and <span style='color: aqua;'>39</span> chance of doing so. All the rules of the game are <span style='color: aqua;'>transferred into the opponent's brain</span> through the domain's sure-hit effect. This is harmless, so as a trade-off the domains activation is extremely fast, less than <span style='color: aqua;'>0.2 seconds</span>.",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Scenarios:</span><span style='font-size:1.1rem'> <br><span style='color: aqua;'>Transit Card Riichi</span>:<span style='color: orange; font-weight:900;'> ★☆☆</span><br>If Yuki passes through the station gate on time to reach work before he is late, jackpot.<br><span style='color: aqua;'>Seat Struggle Riichi</span>:<span style='color: orange; font-weight:900;'> ★★☆</span><br> Not yet revealed.<br><span style='color: aqua;'>Potty Emergency Riichi</span>:<span style='color: orange; font-weight:900;'> ★★☆</span><br> If Hiro reaches Shin-Yurigaoka station without wetting themselves, jackpot.<br><span style='color: aqua;'>Friday Night Final Train Riichi</span>:<span style='color: orange; font-weight:900;'> ★★★</span><br> If Yume doesn't board a train on the opposite side of Yuki and reappears after departure, jackpot.</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Game-Flow:</span> <span style='font-size:1.2rem;'>The game begins in <span style='color: aqua;'>normal</span> mode. As the battle begins, the user can manifest <span style='color: aqua;'>3</span> types of visual effect indicators: <span style='color: aqua;'>shutter doors</span>, <span style='color: aqua;'>reserve balls</span>, and <span style='color: aqua;'>consecutive effects</span>. Doors and balls are <span style='color: aqua;'>offensive</span> attacks, but consecutive effects are <span style='color: aqua;'>defensive</span>, that redo a sequence to revert damage. Doors and reserve balls come in a <span style='color: lightgreen;'>green</span>, <span style='color: red;'> red</span>, or <span style='color: orange;'>gold</span> rarity to symbolize a higher chance at a jackpot. <span style='color: aqua;'>Rainbow-colored </span>indicators or re-doing four consecutive effects <span style='color: aqua;'>guarantees</span> a jackpot.<br><br> The user can choose which visual indicator, but their success is up to luck. Generating one or more visual indicators progresses the stage to a <span style='color: aqua;'>riichi scenario</span> and reveals 2 of 3 of the numbers needed for a jackpot. There are <span style='color: aqua;'>4</span> riichi scenarios with different chances of hitting jackpot, with the final train riichi having over <span style='color: aqua;'>80%</span> chance. The user's opponent cannot <span style='color: aqua;'>obstruct the visualization</span> of the riichi scenarios and must watch it unfold or defeat the caster before it ends.</span>",
    manga:"<span style='color: orange; font-weight:900;'>Manga:</span> Chapter 182",
    anime:"<span style='color: orange; font-weight:900;'>Anime:</span> N/A",
    userimage:"./user/hakari.png",
    domainimage:"./domain/deadly.jpg",
    hakari:"./assets/love.png",
    back:"./domain/gamble.png",
    hand:"./assets/rct.jpg",
    full:"./user/2hakari.png",
},
{
    name:"Deadly Sentencing",
    jname:"Chūbuku Shishi",
    user:"Hiromi Higuruma",
    age:"36",
    species:"Human",
    grade:"N/A",
    domainname:"Deadly Sentencing (Chūbuku Shishi) is Hiromi Higuruma's non-lethal domain expansion.",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span> A defense attourney who often took on impossibly difficult cases in order to protect the wrongfully accused. Having since given up on the justice system completely, Hiromi currently participates in the Culling Game as one of the top players. He is known as a prodigy and learn his ct and domain in <span style='color: aqua;'>2 weeks</span> and <span style='color: aqua;'>reverse curse technique on the spot</span> during his fight with Sukuna.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span> This domain reflects a small <span style='color: aqua;'>courtroom</span> where the user and their target stand across from one another playing the roles of <span style='color: aqua;'>prosecutor</span> and <span style='color: aqua;'>defendant</span>. There are numerous <span style='color: aqua;'>guillotines</span> in the background with chopped-up debris beneath them. With a <span style='color: aqua;'>shikigami</span> called <span style='color: aqua;'>Judgeman</span> that decides the fate of the defendant. The user is given a <span style='color: aqua;'>Gavel</span> that can change size. In the event of a <span style='color: aqua;'>death penalty</span> the Gavel becomes the <span style='color: aqua;'>Executioner's Sword</span>. <br><br>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span> Deadly Sentencing is the type of domain that <span style='color: aqua;'>doesn</span>'t contain a <span style='color: aqua;'>can't-miss attack</span>, instead, it forces those inside to follow the rules of the user's cursed technique. The domain isn't constructed to be lethal and implements a <span style='color: aqua;'>binding vow </span>requiring the user to explain the aforementioned rules. No violence can be done on both sides until the verdict has been made by Judgeman.<br><br><br><br>",
    appear:"./assets/deadly.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span> <span style='font-size:1.1rem;'>The trial-based cursed technique imbued into the domain allows the user to prosecute their target with the shikigami called <span style='color: aqua;'>Judgeman</span>. There is <span style='color: aqua;'>no violence</span> allowed inside the domain for either side and proceedings begin immediately after activation. First Judgeman will announce the charges against the defendant, which are actual crimes they may or may not have committed. Judgeman automatically knows everything about everyone inside the domain but this <span style='color: aqua;'>information</span> isn't shared with the <span style='color: aqua;'>caster</span>. The verdict of the trial depends only on the arguments presented by both sides. After the accusation is reviewed, the defendant is given <span style='color: aqua;'>one</span> chance to defend their case. They have three options: <span style='color: aqua;'>silence, confession,</span> or <span style='color: aqua;'>denial</span>. If the defendant chooses to deny the charges, they can lie in their statements. The defendant's goal is to dispel all doubt and win of <span style='color: aqua;'>innocence</span> from Judgeman.</span>",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Weapon:</span> <span style='font-size:1.1rem;'>In addition to his <span style='color: aqua;'>shikigami</span> and his domain, Hiromi's <span style='color: aqua;'>gavel</span> cursed tool is connected to his innate technique as well. It is a highly versatile weapon that can change its proportions to emulate different weapons, such as a <span style='color: aqua;'>hammer, staff, hook,</span> and <span style='color: aqua;'>giant mallet</span> among other tools. In the event of the Death Penalty, the gavel will change into the <span style='color: aqua;'>Executioner's Sword</span>. Without <span style='color: aqua;'>exception</span>, anyone cut by the Executioner's Sword will die immediately.</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Trial:</span> <span style='font-size:1.1rem;'>The prosecutor also only has <span style='color: aqua;'>one</span> chance to make a statement, but theirs is a <span style='color: aqua;'>rebuttal</span> based on evidence submitted by Judgeman for deliberation. The evidence submitted appears as a <span style='color: aqua;'>sealed envelope</span> in the prosecutor's hand. The evidence submitted is not necessarily conclusive and it will not be opened and shared with the defendant until after their statement, but the prosecutor will be informed of the contained information by Judgeman upon receiving the envelope. Once the prosecution and defense have both made their statements, Judgeman will deliver a <span style='color: aqua;'>lawful verdict</span>. If the defendant is found guilty, they are punished with one of what is implied to be several different sentences. Not even the user can be sure of which sentence their opponent will receive.<br><br>One sentence the Judgeman will commonly give is <span style='color: aqua;'>Confiscation</span>, which prevents them from being able to use <span style='color: aqua;'>cursed techniques</span>. After the verdict, the domain dispels and the punishment immediately affects the guilty party. However, if the defendant is found guilty without an open confession, they can request a <span style='color: aqua;'>retrial</span> that Judgeman cannot deny.  The most severe sentence Judgeman can give is the Death Penalty accompanied by Confiscation. First, Confiscation removes the guilty party's ability to use cursed techniques and then grants the user the Executioner's Sword.</span>",
    manga:"<span style='color: orange; font-weight:900;'>Manga:</span> Chapter 164",
    anime:"<span style='color: orange; font-weight:900;'>Anime:</span> N/A",
    userimage:"./user/higuruma.png",
    domainimage:"",
    domainvid:"",
    hakari:"./assets/weopon.jpg",
    hand:"./assets/judge.jpg",
    back:"./domain/court.png",
    full:"./user/2higur.png",
},
{
    name:"Womb Profusion",
    jname:"Taizō Hen'ya",
    user:"Kenjaku",
    age:"1000+",
    species:"Human",
    grade:"Special Grade",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span>",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <br><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span>",
    appear:"./assets/void.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span>",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span>",
    manga:"Manga: Chapter 205",
    anime:"Anime: N/A",
    userimage:"./user/Kenjaku.png",
    domainimage:"",
    back:"./domain/tomb.png",
    full:"./user/2kenjaku.png",
},
{
    name:"Threefold Affliction",
    jname:"Shikkushikku Shikku",
    user:"Yorozu",
    age:"1000+",
    species:"Human/Incarnation",
    grade:"N/A",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span>",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <br><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span>",
    appear:"./assets/void.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span>",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span>",
    manga:"Manga: Chapter 219",
    anime:"Anime: N/A",
    userimage:"./user/yorozu.png",
    domainimage:"",
    back:"./domain/three.png",
    full:"./user/2yoru.png",
},
{
    name:"Graveyard",
    jname:"Unknown Name",
    user:"Smallpox Deity",
    age:"Unknown",
    species:"Disease Cursed Spirit",
    grade:"Special Grade",
    domainname:"The name of this domain was <span style='color: deepskyblue;'>never</span> revealed all we know is that is that based on a graveyard.",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span> Smallpox Deity (Hōsōgami) is a special grade disease cursed spirit summoned by Pseudo-Geto using Cursed Spirit Manipulation. The name Smallpox Deity was a lie from Pseudo-Geto, as it is actually a Smallpox Hag (Hōsō Babā) by classification. The upper portion of the curse is covered in light-colored hair, Its mouth has two large tusks, and two arms covered in pox bumps.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span> The domain itself is a graveyard befitting the theme of the disease curse's abilities. Surrounded by an errie forest. The forest is surrounding the graveyard all 4 sides where the graveyard is located in the center. The weather and sky look gloom and cold as if your in a storm.<br><br><br>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>How It Works:</span><br><span style='color: deepskyblue;'>Step 1</span>: Left fist into right hand.<br><br><span style='color: deepskyblue;'>Step 2</span>: person gets trapped in a coffin.<br><br><span style='color: deepskyblue;'>Step 3</span>: A huge boulder traps coffin underground.<br><br><span style='color: deepskyblue;'>Step 4</span>: Smalllpox Deity counts to three.",
    appear:"./assets/graveyard.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span> The Smallpox Deity's cursed technique begins when it traps its target inside a cramped <span style='color: deepskyblue;'>coffin</span>. After the target is caught, the curse takes its <span style='color: deepskyblue;'>left</span> fist and lowers it into its <span style='color: deepskyblue;'>right</span> hand. This motion drops a giant <span style='color: deepskyblue;'>gravestone</span> on top of the coffin, dealing heavy damage and burying the coffin underground.<br><br> Once the gravestone is placed, the disease curse begins to countdown from <span style='color: deepskyblue;'>three</span>. If the count reaches one, the target will be infected with smallpox and die.",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span> Gege Akutami wanted to respect those who may have been affected by illnesses smallpox. To honor them he decided to use smallpox as the dieases because it's been eradicated.<br><br><br><br>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span> Geto summons Smallpox Deity to have it battle with Mei Mei. After Geto leaves, Smallpox Deity quickly traps both Mei Mei and her brother Ui Ui within its Domain Expansion. After also trapping Mei Mei within a coffin, Smallpox Deity uses its Grave attack to smash the coffin with a large boulder. Smallpox Deity starts to count down from 3 but Mei Mei quickly smashes the boulder to pieces.<br><br>Smallpox Deity continues to use its grave attack on Mei Mei until Mei Mei has Ui Ui release his cursed energy. Smallpox Deity then uses his attack on Ui Ui but it doesn't work since Ui Ui counters it with simple domain. Mei Mei then distracts Smallpox Deity, so that one of her crows can exorcise Smallpox Deity in exchange for its life.",
    manga:"<span style='color: orange; font-weight:900;'>Manga:</span> Chapter 101",
    anime:"<span style='color: orange; font-weight:900;'>Anime:</span> Episode 36",
    userimage:"./user/smallpox.png",
    domainimage:"",
    hand:"./assets/smallpox.jpg",
    domainvid:"./assets/smallpox.mp4",
    back:"./domain/smallpox.png",
    full:"./user/2smallpox.png",
},
{
    name:"Horizon of the Captivating Skandha",
    jname:"Tau'un Heisen",
    user:"Dagon",
    age:"Unknown",
    species:"Curse Spirit",
    grade:"Special Grade",
    domainname:"Horizon of the Captivating Skandha (Tau'un Heisen) is Dagon's domain expansion using innate technique.",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span> Dagon (Dagon) is an antagonist in the Jujutsu Kaisen series. He was an unregistered special grade cursed spirit aligned with Mahito, Jogo, and Hanami. Dagon was born from the fear of water-based natural disasters and existed as a cursed womb until he evolved during the Shibuya Incident. Dagon had an appearance similar to an aquatic animal like an octopus.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span> Dagon's Domain Expansion is a <span style='color: deepskyblue;'>tropical beach</span> that has a forest of palm trees on one side of the shore and an ocean on the other side, stretching into the distance. It has been described as a calm domain, and its waters are shallow enough for someone to stand in it while close to the beach. The domain has an umbrella and lounge chairs, which Mahito and Geto use frequently.",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span> When Naobito Zenin cut off Dagon's fingers restricting Dagon from creating a hand seal to use his domain expansion, Dagon instead used some sort of <span style='color: deepskyblue;'>seal</span> on his chest which enabled Dagon to use his domain expansion with forming a hand sign. This seal might be similar to the one on the Smallpox Deity stomach but this is just theory.",
    appear:"./assets/beach.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span> Horizon of the Captivating Skandha has a sure-hit technique that allows the shikigami that Dagon creates to automatically hit their target. From the view of the targeted, the fish appear suddenly, making them near-impossible to block as the  <span style='color: deepskyblue;'>shikigami</span> don't exist until they hit the target, instantly devouring their flesh.<br><br>Though the sure-hit effect can be countered, for example when megumi used his domain it to cancel out Dagon's domain it caused the sure-hit effect to be negated. Also using any sort of shielding method such as <span style='color: deepskyblue;'>domain amplification , simple domain</span> or <span style='color: deepskyblue;'>Falling Blossom Emotion</span> can stop the sure-hit effect.",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span> <span style='color: deepskyblue;'>tō</span>(蕩), means <span style='color: deepskyblue;'>charming/captivating</span>. In this case, tau is derived from <span style='color: deepskyblue;'>tayutau</span>(揺蕩う), which means <span style='color: deepskyblue;'>to sway to and fro</span>; <br> <span style='color: deepskyblue;'>un</span>(蘊), can be translated as <span style='color: deepskyblue;'>aggregate; abundance</span>. It also means <span style='color: deepskyblue;'>skandha</span>.<br> <span style='color: deepskyblue;'>heisen</span> (平線), means <span style='color: deepskyblue;'>horizon</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span> Dagon was able to expand his domain when he was still a <span style='color: deepskyblue;'>Cursed Womb</span>. It is shown that he used his domain first time within an apartment to relax in the water while Mahito was sitting on the beach. Kenjaku commented that Dagon has quite the calm domain. Later, this domain has been used frequently for similar purposes.<br><br>Later in Shibuya, after becoming a fully developed Cursed Spirit he utilized his domain again against Kento Nanami, Maki Zenin, and Naobito Zenin. He used his Shikigami to attack them. However, Megumi broke into his domain by expanding his domain which lead to a <span style='color: deepskyblue;'>battle of domains</span> and <span style='color: deepskyblue;'>negating</span> Dagon's sure-hit technique.",
    manga:"<span style='color: orange; font-weight:900;'>Manga:</span> Chapter 16",
    anime:"<span style='color: orange; font-weight:900;'>Anime:</span> Episode 7",
    userimage:"./user/dagon.png",
    hand:"./assets/seal.jpg",
    domainimage:"",
    domainvid:"./assets/beach.mp4",
    back:"./domain/skandha.png",
    full:"./user/2dagon.png",
},
{
    name:"Coffin of the Iron Mountain",
    jname:"Gaikan Tecchisen",
    user:"Jogo",
    age:"Unknown",
    species:"Curse Spirit",
    grade:"Special Grade",
    domainname:"Coffin of the Iron Mountain (Gaikan Tecchisen) is Jogo's domain expansion using his innate technique.",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span> Jogo is a major antagonist in the Jujutsu Kaisen series. He is an unregistered special grade cursed spirit. Jogo believed curses were the true humans and desired a world where his kind dominated the earth. Jogo has a humanoid shape but his physical appearance is distinctly a cursed spirit. Jogo carries himself like an <span style='color: deepskyblue;'>elderly</span> man. He is short, hunchback, and carried a cane.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span> The environment constructed by this domain resembles the inside of an active <span style='color: deepskyblue;'>volcano</span>. It is a sealed-off stone chamber with large fissures across the walls and the ground that spout large portions of magma. It is stated that the environment in his domain is <span style='color: deepskyblue;'>tangible</span> and the magma produce an ambient amount of heat.<br><br>" ,
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span> He was born of humanity's <span style='color: deepskyblue;'>fear</span> and <span style='color: deepskyblue;'>negative association</span> with volcanoes and other fire-related natural disasters. This resulted in a highly intelligent cursed spirit with massive levels of cursed energy even for a special grade.<br><br> Jogo in the same vein of strength as <span style='color: deepskyblue;'>eight</span> or <span style='color: deepskyblue;'>nine</span> of Sukuna's fingers.",
    appear:"./assets/iron.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span> Coffin of the Iron Mountain is a lethal domain that includes a guaranteed hit. The user can command <span style='color: deepskyblue;'>molten rock</span> that extends from the environment to hit their opponent with a can't-miss attack.<br><br>Non-sorcerers would <span style='color: deepskyblue;'>combust</span> in Jogo's very presence if he simply activated his cursed technique. Jujutsu sorcerers who entered his domain would suffer a similar fate. Jogo's mere presence causing non-sorcerers to combust.",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span> <span style='color: deepskyblue;'>Gaikan</span> (蓋棺) refers to the lid/lidding of a <span style='color: deepskyblue;'>casket</span>. <br><br><span style='color: deepskyblue;'>Tecchisen</span> (鉄囲山) comes from <span style='color: deepskyblue;'>the legend of nine mountains and eight seas</span> of ancient Indian cosmology, which exists in Hinduism and Buddhism.",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span> Jogo first displayed his Domain Expansion when he was desperate to kill Satoru Gojo in their fight. In order to bypass Satoru's Infinity, Jogo needed to employ his can't-miss attacks. While a normal sorcerer would burn up inside Coffin of the Iron Mountain, Satoru was unharmed and was able to protect his student. <br><br>Determined to leave Satoru burned beyond a pile of ash, Jogo attempted to ramp up the cursed techniques. However, Satoru expanded his Unlimited Void, which proved to be the more refined of the two domains, and quickly suppressed Coffin of the Iron Mountain.",
    manga:"<span style='color: orange; font-weight:900;'>Manga:</span> Chapter 15",
    anime:"<span style='color: orange; font-weight:900;'>Anime:</span> Episode 7",
    hand:"./assets/combust.jpg",
    userimage:"./user/jogo.png",
    domainimage:"",
    domainvid:"./assets/iron.mp4",
    back:"./domain/mountain.png",
    full:"./user/2jogo.png",
},
{
    name:"Self-Embodiment of Perfection",
    jname:"Jihei Endonka",
    user:"Mahito",
    age:"Unknown",
    species:"Curse Spirit",
    grade:"Special Grade",
    domainname:"Self-Embodiment of Perfection (Jihei Endonka) is Mahito's domain expansion using Idle Transfiguration.",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span> Mahito is one of the primary antagonists of the Jujutsu Kaisen series. He is an unregistered special grade cursed spirit allied with Pseudo-Geto. He is also the leader of his own group, consisting of Jogo, Hanami, and Dagon. His group's ultimate goal is the eradication of humanity and ultimately replacing the population with cursed spirits.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span> This Domain Expansion is conjured by hand seals formed by tiny hands inside Mahito's mouth. This creates a large black environment that presents Mahito's target with giant hands clasped together to form a flower-like shape. Connected to these hands are multiple arms that grabbing one another to form a net pattern that surrounds Mahito's target.",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span> Unlike other sorcerers with domain expansion using two hands to create a hand seal to use their domains. Mahito uses <span style='color: deepskyblue;'>four hands</span> making <span style='color: deepskyblue;'>two hand</span> seals formed by tiny hands inside Mahito's mouth.<br> Though shown in the in <span style='color: deepskyblue;'>season 2 episode 21</span> Mahito does a one hand sign with his original hands.",
    appear:"./assets/self.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span> Self-Embodiment of Perfection increases the effectiveness of Mahito's Idle Transfiguration cursed technique by allowing him to transfigure the souls of the targets within his domain without requiring physical contact. Nanami described the experience of being inside Mahito's Domain as akin to literally being in the palm of Mahito's hand. Alongside Satoru Gojo's Unlimited Void, Kento Nanami said Self-Embodiment of Perfection is an almost guaranteed victory for the caster.<br><br> However, a major drawback of this ability is that Mahito is forced to touch the souls of <span style='color: deepskyblue;'>everyone</span> inside the domain, which backfires when Itadori entered the domain from the outside, causing Mahito to, unintentionally, touch Sukuna's soul a second time, prompting the King of Curses to lash out at Mahito.",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span> <span style='color: deepskyblue;'>Jihei</span> (自閉), is a term referring to a state of social <span style='color: deepskyblue;'>withdrawal</span> or <span style='color: deepskyblue;'>isolation</span>.<br> <span style='color: deepskyblue;'>Endon</span> (円頓) is a Tendai Buddhist term referring to the quick, perfect reaching of <span style='color: deepskyblue;'>enlightenment</span>.<br>ka (裹?), means <span style='color: deepskyblue;'>conceal wrap up</span>.",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span> After being inspired by his battle against Gojo and awakening a better understanding of the essence of cursed energy from landing a Black Flash on Yuji earlier, Mahito learned how to activate his Domain Expansion for <span style='color: deepskyblue;'>0.2</span> seconds by shortening the processes of realizing his innate domain and activating his cursed technique into one process.<br><br> He demonstrated this feat against Yuji and Aoi Todo, successfully using Idle Transfiguration on Aoi without touching him. Due to the short amount of time the domain expansion lasted, Mahito was able to avoid being attacked by Sukuna despite touching his soul.",
    manga:"<span style='color: orange; font-weight:900;'>Manga:</span> Chapter 29",
    anime:"<span style='color: orange; font-weight:900;'>Anime:</span> Episode 13",
    userimage:"./user/mahito.png",
    hand:"./assets/mahito-hand.jpg",
    domainimage:"",
    domainvid:"./assets/self.mp4",
    back:"./domain/perfect.png",
    full:"./user/2mahito.png",
},
];

export {sorcerer}