const sorcerer = [
    {
    name:"Malevolent Shrine",
    jname:"Fukuma Mizushi",
    user:"Ryomen Sukuna",
    age:"1000+",
    species:"Human/Incarnation",
    grade:"Special Grade",
    domainname:"Malevolent Shrine (Fukuma Mizushi) is Sukuna's domain expansion.",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span> Ryomen Sukuna, is the strongest jujutsu sorcerer from a thousand years ago. Regarded as the undisputed King of Curses, Sukuna is one of the primary antagonists of the Jujutsu Kaisen series. According to legend, Sukuna was an Imaginary Demon during the Heian Era but in truth he was a sorcerer also known as the Disgraced One. Sukuna is around 1000+ years old and was a human now incarnate using the boding of itadori as his host.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span> Malevolent Shrine constructs an environment centered around a small,  Buddhist shrine that has been distorted to instead enshrine demons. It is surrounded by dark-colored water and horned, bull-like skulls on the ground. Human skulls that hang down from it. The four entrances to the shrine are formed by large, grotesque mouths, complete with humanlike teeth and tongues.",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span> Sukuna has the ability to expand his domain without closing the barrier. Creating a binding vow due to allowing an escape route from the domain that enables him to expand the range of the guaranteed-hit up to a maximum radius of <span style='color: deepskyblue;'>200 meters</span>. Malevolent Shrine cannot be destroyed because of the lack of an enclosed barrier. ",
    appear:"./assets/shrine.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span> Malevolent Shrine's guaranteed-hit ability can be made to relentlessly slash apart anything until nothing but dust remains of what has caught in the effective range, via Sukuna's two types of slashing attacks: Cleave and Dismantle, which only cease when the domain is disengaged or Sukuna is so badly injured he can not sustain the domain anymore. Sukuna can set which of the two attacks to use against specific types of targets, such as using <span style='color: deepskyblue;'>Dismantle</span> for inanimate objects and <span style='color: deepskyblue;'>Cleave</span> for subjects with cursed energy.",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span> fukuma(伏魔), comes from fukumaden(伏魔殿), referring to a palace where demons lurk, and is also translatable as <span style='color: deepskyblue;'>Pandemonium</span>.<br>Honorific prefix mi(御), a zushi(厨子) is a miniature, double-doored Buddhist shrine or zu/kuriya(厨) meaning <span style='color: deepskyblue;'>Kitchen</span>.",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span> During his battle with Satoru Gojo, Sukuna expanded his domain a total of <span style='color: deepskyblue;'>three</span> times. As previously mentioned, Malevolent Shrine can equal Unlimited Void in a domain clash, but that is only the case inside a barrier.<br><br> Malevolent Shrine's range reached beyond Unlimited Void's barrier during the first clash of domains. With a domain's barrier being weak to attacks on its outer shell, Gojo's domain was crushed by Malevolent Shrine's slashing attacks and he was immediately struck by its can't-miss attack. <br><br>Later in the fight, Sukuna revealed that he can change the conditions of his domain with a binding vow, such as removing Malevolent Shrine's guaranteed-hit effect within Unlimited Void's effective area or narrowing down its effective range similar to when it was used in Shibuya in exchange for increased power to counter Gojo's Unlimited Void's reinforced outer shell, collapsing it a second time.",
    userimage:"./user/sukuna3.png",
    hand:"./assets/200.jpg",
    domainimage:"./assets/shrine.jpg",
    domainvid:"./assets/cleave.mp4",
    back:"./domain/shrine.png", 
    full:"./user/2sukuna.png",
    manga:"<span style='color: orange; font-weight:900;'>Manga:</span> Chapter 8",
    anime:"<span style='color: orange; font-weight:900;'>Anime:</span> Episode 4",
},
{
    name:"Unlimited Void",
    jname:"Muryōkūsho",
    user:"Satoru Gojo",
    age:"29",
    species:"Human",
    grade:"Special Grade",
    domainname:"Unlimited Void (Muryōkūsho?) is Satoru Gojo's domain expansion.",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span> Satoru Gojo is one of the main protagonists of the Jujutsu Kaisen series. He is a special grade jujutsu sorcerer and widely recognized as the strongest in the world. Satoru is the pride of the Gojo Clan, the first person to inherit both the Limitless and the Six Eyes in four hundred years. He works as a teacher at the Tokyo Jujutsu High and uses his influence to protect and train strong young allies. He is a human born <span style='color: deepskyblue;'>December 7, 1989</span> making him <span style='color: deepskyblue;'>29</span>.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span> This otherworldly space is characterized by a vast and seemingly infinite swirling blackness, devoid of any discernible landmarks or boundaries. The atmosphere is thick with an eerie energy. Inky black tendrils and ethereal shadows weaves through the void, giving it an almost liquid quality. In the center what seems to be a black hole this domain seems as if there are in space.",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span> Unlimited Void is one of, if not the most advanced technique in the arsenal of the Limitless. Satoru Gojo inherited the <span style='color: deepskyblue;'>Six Eyes</span> and likely mastered his Domain Expansion after awakening his full potential after the Star Plasma Vessel escort mission. He first displayed his mastery over his domain when he used it to counter Jogo's domain.",
    appear:"./assets/void.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span> This Domain Expansion brings the user and their targets inside the Limitless itself, a vast void of infinite knowledge. Boundless raw information floods into the target's mind, overwhelming them to the point where they're completely immobilized. Alongside Self-Embodiment of Perfection, Nanami considered Unlimited Void an almost-guaranteed win once it ensnares its target.<br><br>The complete incapacitation of the target is caused by a phenomenon where the target will be able to see and feel everything while not being able to see or feel anything at the same time. All the actions one has taken in their life is forced upon them infinitely and they can't do anything but die slowly. This effect does not affect the user or anyone they're touching.",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span> 無量空処 (Muryōkūsho) is a Buddhist term that can be translated as the <span style='color: deepskyblue;'>Unlimited Void</span> or <span style='color: deepskyblue;'>Infinite Space</span>.<br> Often used in the context of Buddhist philosophy to describe a boundless and infinite space transcending conventional notions of physical dimensions.",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span>  Satoru surprised everyone and activated an all-or-nothing Domain Expansion of just <span style='color: deepskyblue;'>0.2 seconds</span>. Figuring that a non-sorcerer could only last 0.2 seconds within the domain without suffering aftereffects. The amount of information that everyone was exposed to was about half a year's worth, leaving everyone unconscious while still standing. This level of the domain could've allowed the cursed spirits to awaken from their trance at any moment, so Satoru focused on eliminating all one thousand of the transfigured humans targeting the civilians in just 299 seconds.<br><br>During Satoru's duel with Sukuna, he expanded Unlimited Void a total of <span style='color: deepskyblue;'>five</span> times. The two of them simultaneously activated Domain Expansion after various well-matched exchanges. Unlimited Void proved to be as equally strong as Sukuna's Malevolent Shrine, neutralising both of their guaranteed-hit effects.",
    domainimage:"",
    hand:"./assets/eyes.jpg",
    domainvid:"./assets/void.mp4",
    manga:"<span style='color: orange; font-weight:900;'>Manga:</span> Chapter 15",
    anime:"<span style='color: orange; font-weight:900;'>Anime:</span> Episode 7",
    userimage:"./user/gojo.png",
    back:"./domain/void.png",
    full:"./user/1gojo.png",
},
{
    name:"Chimera Shadow Garden",
    jname:"Kangō An'eitei",
    user:"Megumi Fushiguro",
    age:"16",
    species:"Human",
    grade:"Grade 2",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span>",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <br><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span>",
    appear:"./assets/void.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span>",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span>",
    manga:"Manga: Chapter 58",
    anime:"Anime: Episode 23",
    userimage:"./user/megumi.png",
    domainimage:"",
    back:"./domain/chimera.png",
    full:"./user/2megumi.png",
},
{
    name:"Time Cell Moon Palace",
    jname:"Jihō Gekkyūden",
    user:"Naoya Zenin",
    age:"27",
    species:"Human/Vengeful Curse",
    grade:"Special Grade 1",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span>",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <br><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span>",
    appear:"./assets/void.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span>",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span>",
    manga:"Manga: Chapter 198",
    anime:"Anime: N/A",
    userimage:"./user/naoya.png",
    domainimage:"",
    back:"./domain/cell1.png",
    full:"./user/2naoya.png",
},
{
    name:"Idle Death Gamble",
    jname:"Zasatsu Bakuto",
    user:"Kinji Hakari",
    age:"Unknown",
    species:"Human",
    grade:"Suspended",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span>",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <br><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span>",
    appear:"./assets/void.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span>",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span>",
    manga:"Manga: Chapter 182",
    anime:"Anime: N/A",
    userimage:"./user/hakari.png",
    domainimage:"./domain/deadly.jpg",
    back:"./domain/gamble.png",
    full:"./user/2hakari.png",
},
{
    name:"Deadly Sentencing",
    jname:"Chūbuku Shishi",
    user:"Hiromi Higuruma",
    age:"36",
    species:"Human",
    grade:"N/A",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span>",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <br><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span>",
    appear:"./assets/void.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span>",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span>",
    manga:"Manga: Chapter 164",
    anime:"Anime: N/A",
    userimage:"./user/higuruma.png",
    domainimage:"",
    back:"./domain/court.png",
    full:"./user/2higur.png",
},
{
    name:"Womb Profusion",
    jname:"Taizō Hen'ya",
    user:"Kenjaku",
    age:"1000+",
    species:"Human",
    grade:"Special Grade",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span>",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <br><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span>",
    appear:"./assets/void.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span>",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span>",
    manga:"Manga: Chapter 205",
    anime:"Anime: N/A",
    userimage:"./user/Kenjaku.png",
    domainimage:"",
    back:"./domain/tomb.png",
    full:"./user/2kenjaku.png",
},
{
    name:"Threefold Affliction",
    jname:"Shikkushikku Shikku",
    user:"Yorozu",
    age:"1000+",
    species:"Human/Incarnation",
    grade:"N/A",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span>",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <br><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span>",
    appear:"./assets/void.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span>",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span>",
    manga:"Manga: Chapter 219",
    anime:"Anime: N/A",
    userimage:"./user/yorozu.png",
    domainimage:"",
    back:"./domain/three.png",
    full:"./user/2yoru.png",
},
{
    name:"Unknown Name",
    jname:"Unknown Name",
    user:"Smallpox Deity",
    age:"Unknown",
    species:"Disease Cursed Spirit",
    grade:"Special Grade",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span>",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <br><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span>",
    appear:"./assets/void.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span>",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span>",
    manga:"Manga: Chapter 101",
    anime:"Anime: Episode 36",
    userimage:"./user/smallpox.png",
    domainimage:"",
    back:"./domain/smallpox.png",
    full:"./user/1mahito.png",
},
{
    name:"Horizon of the Captivating Skandha",
    jname:"Tau'un Heisen",
    user:"Dagon",
    age:"Unknown",
    species:"Curse Spirit",
    grade:"Special Grade",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span>",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <br><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span>",
    appear:"./assets/void.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span>",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span>",
    manga:"Manga: Chapter 16",
    anime:"Anime: Episode 7",
    userimage:"./user/dagon.png",
    domainimage:"",
    back:"./domain/skandha.png",
    full:"./user/2dagon.png",
},
{
    name:"Coffin of the Iron Mountain",
    jname:"Gaikan Tecchisen",
    user:"Jogo",
    age:"Unknown",
    species:"Curse Spirit",
    grade:"Special Grade",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span>",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <br><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span>",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span>",
    appear:"./assets/void.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span>",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span>",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span>",
    manga:"Manga: Chapter 15",
    anime:"Anime: Episode 7",
    userimage:"./user/jogo.png",
    domainimage:"",
    back:"./domain/mountain.png",
    full:"./user/2jogo.png",
},
{
    name:"Self-Embodiment of Perfection",
    jname:"Jihei Endonka",
    user:"Mahito",
    age:"Unknown",
    species:"Curse Spirit",
    grade:"Special Grade",
    domainname:"Self-Embodiment of Perfection (Jihei Endonka) is Mahito's domain expansion using Idle Transfiguration.",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Summary:</span> Mahito is one of the primary antagonists of the Jujutsu Kaisen series. He is an unregistered special grade cursed spirit allied with Pseudo-Geto. He is also the leader of his own group, consisting of Jogo, Hanami, and Dagon. His group's ultimate goal is the eradication of humanity and ultimately replacing the population with cursed spirits.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Appearance:</span> This Domain Expansion is conjured by hand seals formed by tiny hands inside Mahito's mouth. This creates a large black environment that presents Mahito's target with giant hands clasped together to form a flower-like shape. Connected to these hands are multiple arms that grabbing one another to form a net pattern that surrounds Mahito's target.",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Extra:</span> Unlike other sorcerers with domain expansion using two hands to create a hand seal to use their domains. Mahito uses <span style='color: deepskyblue;'>four hands</span> making <span style='color: deepskyblue;'>two hand</span> seals formed by tiny hands inside Mahito's mouth.<br> Though shown in the in <span style='color: deepskyblue;'>season 2 episode 21</span> Mahito does a one hand sign with his original hands.",
    appear:"./assets/self.jpg",
    domaininfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Ability:</span> Self-Embodiment of Perfection increases the effectiveness of Mahito's Idle Transfiguration cursed technique by allowing him to transfigure the souls of the targets within his domain without requiring physical contact. Nanami described the experience of being inside Mahito's Domain as akin to literally being in the palm of Mahito's hand. Alongside Satoru Gojo's Unlimited Void, Kento Nanami said Self-Embodiment of Perfection is an almost guaranteed victory for the caster.<br><br> However, a major drawback of this ability is that Mahito is forced to touch the souls of <span style='color: deepskyblue;'>everyone</span> inside the domain, which backfires when Itadori entered the domain from the outside, causing Mahito to, unintentionally, touch Sukuna's soul a second time, prompting the King of Curses to lash out at Mahito.",
    translation:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Translate:</span> Jihei (自閉), is a term referring to a state of social <span style='color: deepskyblue;'>withdrawal</span> or <span style='color: deepskyblue;'>isolation</span>.<br> Endon (円頓) is a Tendai Buddhist term referring to the quick, perfect reaching of <span style='color: deepskyblue;'>enlightenment</span>.<br>ka (裹?), means <span style='color: deepskyblue;'>conceal wrap up</span>.",
    lore:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span style='color: orange; font-weight:900;'>Usage:</span> After being inspired by his battle against Gojo and awakening a better understanding of the essence of cursed energy from landing a Black Flash on Yuji earlier, Mahito learned how to activate his Domain Expansion for <span style='color: deepskyblue;'>0.2</span> seconds by shortening the processes of realizing his innate domain and activating his cursed technique into one process.<br><br> He demonstrated this feat against Yuji and Aoi Todo, successfully using Idle Transfiguration on Aoi without touching him. Due to the short amount of time the domain expansion lasted, Mahito was able to avoid being attacked by Sukuna despite touching his soul.",
    manga:"<span style='color: orange; font-weight:900;'>Manga:</span> Chapter 29",
    anime:"<span style='color: orange; font-weight:900;'>Anime:</span> Episode 13",
    userimage:"./user/mahito.png",
    hand:"./assets/mahito-hand.jpg",
    domainimage:"",
    domainvid:"./assets/self.mp4",
    back:"./domain/perfect.png",
    full:"./user/2mahito.png",
},
];

export {sorcerer}