const sorcerer = [
    {
    name:"Malevolent Shrine",
    jname:"Fukuma Mizushi",
    user:"Ryomen Sukuna",
    age:"1000+",
    species:"Human/Incarnation",
    grade:"Special Grade",
    userinfo:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspSummary: Ryomen Sukuna, is the strongest jujutsu sorcerer from a thousand years ago. Regarded as the undisputed King of Curses, Sukuna is one of the primary antagonists of the Jujutsu Kaisen series. According to legend, Sukuna was an Imaginary Demon during the Heian Era but in truth he was a sorcerer also known as the Disgraced One. Sukuna is around 1000+ years old and was a human now incarnate using the boding of itadori as his host.",
    domain:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspMalevolent Shrine (Fukuma Mizushi) is Sukuna's domain expansion.<br><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Appearance: Malevolent Shrine constructs an environment centered around a small, disfeatured Buddhist shrine that has been distorted to instead enshrine demons. It is surrounded by dark-colored water and horned, bull-like skulls on the ground. The roof also has horns coming out of it, along with human skulls that hang down from it. The four entrances to the shrine are formed by large, grotesque mouths, complete with humanlike teeth and tongues.",
    extra:"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspExtra: Sukuna has the ability to expand his domain without closing the barrier. This creates a binding vow due to allowing an escape route from the domain that enables him to expand the range of the guaranteed-hit up to a maximum radius of 200 meters. Unlike other domains which operate with an outer shell and can be cancelled if destroyed, Malevolent Shrine cannot be destroyed because of the lack of an enclosed barrier. ",
    appear:"./assets/shrine.jpg",
    manga:"Manga: Chapter 8",
    anime:"Anime: Episode 4",
    userimage:"./user/sukuna3.png",
    domainimage:"",
    back:"./domain/shrine.png",
   
    full:"./user/2sukuna.png",
},
{
    name:"Unlimited Void",
    jname:"Muryōkūsho",
    user:"Satoru Gojo",
    age:"29",
    species:"Human",
    grade:"Special Grade",
    userinfo:"",
    domain:"",
    manga:"Manga: Chapter 15",
    anime:"Anime: Episode 7",
    userimage:"./user/gojo.png",
    domainimage:"",
    back:"./domain/void.png",
    extra:"",
    full:"./user/1gojo.png",
},
{
    name:"Chimera Shadow Garden",
    jname:"Kangō An'eitei",
    user:"Megumi Fushiguro",
    age:"16",
    species:"Human",
    grade:"Grade 2",
    userinfo:"",
    domain:"",
    manga:"Manga: Chapter 58",
    anime:"Anime: Episode 23",
    userimage:"./user/megumi.png",
    domainimage:"",
    back:"./domain/chimera.png",
    extra:"",
    full:"./user/2megumi.png",
},
{
    name:"Time Cell Moon Palace",
    jname:"Jihō Gekkyūden",
    user:"Naoya Zenin",
    age:"27",
    species:"Human/Vengeful Curse",
    grade:"Special Grade 1",
    userinfo:"",
    domain:"",
    manga:"Manga: Chapter 198",
    anime:"Anime: N/A",
    userimage:"./user/naoya.png",
    domainimage:"",
    back:"./domain/cell1.png",
    extra:"",
    full:"./user/2naoya.png",
},
{
    name:"Idle Death Gamble",
    jname:"Zasatsu Bakuto",
    user:"Kinji Hakari",
    age:"Unknown",
    species:"Human",
    grade:"Suspended",
    userinfo:"",
    domain:"",
    manga:"Manga: Chapter 182",
    anime:"Anime: N/A",
    userimage:"./user/hakari.png",
    domainimage:"./domain/deadly.jpg",
    back:"./domain/gamble.png",
    extra:"",
    full:"./user/2hakari.png",
},
{
    name:"Deadly Sentencing",
    jname:"Chūbuku Shishi",
    user:"Hiromi Higuruma",
    age:"36",
    species:"Human",
    grade:"N/A",
    userinfo:"",
    domain:"",
    manga:"Manga: Chapter 164",
    anime:"Anime: N/A",
    userimage:"./user/higuruma.png",
    domainimage:"",
    back:"./domain/court.png",
    extra:"",
    full:"./user/2higur.png",
},
{
    name:"Womb Profusion",
    jname:"Taizō Hen'ya",
    user:"Kenjaku",
    age:"1000+",
    species:"Human",
    grade:"Special Grade",
    userinfo:"",
    domain:"",
    manga:"Manga: Chapter 205",
    anime:"Anime: N/A",
    userimage:"./user/Kenjaku.png",
    domainimage:"",
    back:"./domain/tomb.png",
    extra:"",
    full:"./user/2kenjaku.png",
},
{
    name:"Threefold Affliction",
    jname:"Shikkushikku Shikku",
    user:"Yorozu",
    age:"1000+",
    species:"Human/Incarnation",
    grade:"N/A",
    userinfo:"",
    domain:"",
    manga:"Manga: Chapter 219",
    anime:"Anime: N/A",
    userimage:"./user/yorozu.png",
    domainimage:"",
    back:"./domain/three.png",
    extra:"",
    full:"./user/2yoru.png",
},
{
    name:"Unknown Name",
    jname:"Unknown Name",
    user:"Smallpox Deity",
    age:"Unknown",
    species:"Disease Cursed Spirit",
    grade:"Special Grade",
    userinfo:"",
    domain:"",
    manga:"Manga: Chapter 101",
    anime:"Anime: Episode 36",
    userimage:"./user/smallpox.png",
    domainimage:"",
    back:"./domain/smallpox.png",
    extra:"",
    full:"./user/1mahito.png",
},
{
    name:"Horizon of the Captivating Skandha",
    jname:"Tau'un Heisen",
    user:"Dagon",
    age:"Unknown",
    species:"Curse Spirit",
    grade:"Special Grade",
    userinfo:"",
    domain:"",
    manga:"Manga: Chapter 16",
    anime:"Anime: Episode 7",
    userimage:"./user/dagon.png",
    domainimage:"",
    back:"./domain/skandha.png",
    extra:"",
    full:"./user/2dagon.png",
},
{
    name:"Coffin of the Iron Mountain",
    jname:"Gaikan Tecchisen",
    user:"Jogo",
    age:"Unknown",
    species:"Curse Spirit",
    grade:"Special Grade",
    userinfo:"",
    domain:"",
    manga:"Manga: Chapter 15",
    anime:"Anime: Episode 7",
    userimage:"./user/jogo.png",
    domainimage:"",
    back:"./domain/mountain.png",
    extra:"",
    full:"./user/2jogo.png",
},
{
    name:"Self-Embodiment of Perfection",
    jname:"Jihei Endonka",
    user:"Mahito",
    age:"Unknown",
    species:"Curse Spirit",
    grade:"Special Grade",
    userinfo:"",
    domain:"",
    manga:"Manga: Chapter 29",
    anime:"Anime: Episode 13",
    userimage:"./user/mahito.png",
    domainimage:"",
    back:"./domain/perfect.png",
    extra:"",
    full:"./user/2mahito.png",
},
];

export {sorcerer}